version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: fsdbsdmsd
      MYSQL_DATABASE: school
      # MYSQL_PASSWORD: saifpass
      # MYSQL_USER: saif
    command: --skip-grant-tables
    ports:
      - 3307:3306
    restart: always
    networks:
      - sila-test
      
  myapp:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mysql
    restart: always
    environment:
      DB_USER: root
      DB_PASS: fsdbsdmsd
      DB_HOST: localhost:3306
      DB_NAME: school
    networks:
      - sila-test

volumes:
  mysql_data:

networks:
  sila-test:
    driver: bridge