version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql-dummy
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: college
    networks:
      - sila-test
    command: ["mysql", "-h", "localhost", "-u", "root", "-pcollege", "-e", "CREATE DATABASE IF NOT EXISTS school;"]
  myapp:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mysql
    restart: always
    environment:
      DB_USER: root
      DB_PASS: college
      DB_HOST: mysql:3306
      DB_NAME: school
    command: ["sh", "-c", "sleep 10 && python /home/app/main.py"]
    networks:
      - sila-test
    volumes: 
      - /home/syedbaqarabbas/Downloads/Sila:/home

networks:
  sila-test:
    driver: bridge